export const categories = ['Education', 'Corporate', 'Events', 'Custom'];

export const templates = [
  {
    id: 'completion',
    name: 'Certificate of Completion',
    category: 'Education',
    description: 'Classic completion certificate for courses and programs',
    colors: { primary: '#1a365d', secondary: '#c6a84e', background: '#fffef7', text: '#1a202c', border: '#c6a84e' },
    borderStyle: 'ornate',
    sealStyle: 'gold-seal',
    titleLine1: 'CERTIFICATE',
    titleLine2: 'OF COMPLETION',
    defaultDescription: 'has successfully completed all requirements of',
  },
  {
    id: 'achievement',
    name: 'Achievement Award',
    category: 'Corporate',
    description: 'Prestigious award for outstanding achievement',
    colors: { primary: '#4c1d95', secondary: '#d4a017', background: '#fefcf3', text: '#1c1917', border: '#d4a017' },
    borderStyle: 'elegant',
    sealStyle: 'shield',
    titleLine1: 'ACHIEVEMENT',
    titleLine2: 'AWARD',
    defaultDescription: 'is hereby recognized for outstanding achievement in',
  },
  {
    id: 'appreciation',
    name: 'Certificate of Appreciation',
    category: 'Corporate',
    description: 'Express gratitude with an elegant appreciation certificate',
    colors: { primary: '#065f46', secondary: '#92400e', background: '#fefdf5', text: '#1c1917', border: '#065f46' },
    borderStyle: 'classic',
    sealStyle: 'laurel',
    titleLine1: 'CERTIFICATE',
    titleLine2: 'OF APPRECIATION',
    defaultDescription: 'is sincerely appreciated for their valuable contribution to',
  },
  {
    id: 'training',
    name: 'Training Certificate',
    category: 'Education',
    description: 'Professional certificate for training programs',
    colors: { primary: '#334155', secondary: '#3b82f6', background: '#f8fafc', text: '#0f172a', border: '#3b82f6' },
    borderStyle: 'modern',
    sealStyle: 'none',
    titleLine1: 'TRAINING',
    titleLine2: 'CERTIFICATE',
    defaultDescription: 'has successfully completed the training program for',
  },
  {
    id: 'course-completion',
    name: 'Course Completion Certificate',
    category: 'Education',
    description: 'Academic certificate for completing courses',
    colors: { primary: '#7f1d1d', secondary: '#b8860b', background: '#fefcf3', text: '#1c1917', border: '#b8860b' },
    borderStyle: 'formal',
    sealStyle: 'gold-seal',
    titleLine1: 'CERTIFICATE',
    titleLine2: 'OF COURSE COMPLETION',
    defaultDescription: 'has successfully completed the course',
  },
  {
    id: 'event-participation',
    name: 'Event Participation Certificate',
    category: 'Events',
    description: 'Certificate for event attendees and participants',
    colors: { primary: '#0f766e', secondary: '#fb923c', background: '#f0fdfa', text: '#134e4a', border: '#0f766e' },
    borderStyle: 'modern',
    sealStyle: 'star-badge',
    titleLine1: 'CERTIFICATE',
    titleLine2: 'OF PARTICIPATION',
    defaultDescription: 'has participated in',
  },
  {
    id: 'employee-of-month',
    name: 'Employee of the Month',
    category: 'Corporate',
    description: 'Recognize top employees with this premium award',
    colors: { primary: '#0f172a', secondary: '#eab308', background: '#fffef5', text: '#0f172a', border: '#eab308' },
    borderStyle: 'formal',
    sealStyle: 'shield',
    titleLine1: 'EMPLOYEE',
    titleLine2: 'OF THE MONTH',
    defaultDescription: 'is recognized as Employee of the Month for exceptional performance at',
  },
  {
    id: 'best-performance',
    name: 'Best Performance Award',
    category: 'Corporate',
    description: 'Award for exceptional performance',
    colors: { primary: '#991b1b', secondary: '#f59e0b', background: '#fef9f0', text: '#1c1917', border: '#991b1b' },
    borderStyle: 'ornate',
    sealStyle: 'star-badge',
    titleLine1: 'BEST PERFORMANCE',
    titleLine2: 'AWARD',
    defaultDescription: 'is awarded for best performance in',
  },
  {
    id: 'sports-achievement',
    name: 'Sports Achievement Certificate',
    category: 'Events',
    description: 'Dynamic certificate for sports and athletic achievements',
    colors: { primary: '#1e40af', secondary: '#ea580c', background: '#eff6ff', text: '#1e3a5f', border: '#1e40af' },
    borderStyle: 'modern',
    sealStyle: 'ribbon-badge',
    titleLine1: 'SPORTS',
    titleLine2: 'ACHIEVEMENT',
    defaultDescription: 'is awarded for outstanding achievement in',
  },
  {
    id: 'academic-excellence',
    name: 'Academic Excellence Award',
    category: 'Education',
    description: 'Recognize academic brilliance and scholarly achievement',
    colors: { primary: '#581c87', secondary: '#94a3b8', background: '#faf5ff', text: '#2e1065', border: '#581c87' },
    borderStyle: 'elegant',
    sealStyle: 'laurel',
    titleLine1: 'ACADEMIC',
    titleLine2: 'EXCELLENCE AWARD',
    defaultDescription: 'is recognized for academic excellence in',
  },
  {
    id: 'internship',
    name: 'Internship Certificate',
    category: 'Education',
    description: 'Modern certificate for internship completion',
    colors: { primary: '#9f1239', secondary: '#fda4af', background: '#fff1f2', text: '#1c1917', border: '#9f1239' },
    borderStyle: 'minimal',
    sealStyle: 'none',
    titleLine1: 'INTERNSHIP',
    titleLine2: 'CERTIFICATE',
    defaultDescription: 'has successfully completed their internship at',
  },
  {
    id: 'volunteer',
    name: 'Volunteer Certificate',
    category: 'Events',
    description: 'Thank volunteers with a warm appreciation certificate',
    colors: { primary: '#92400e', secondary: '#84cc16', background: '#fefce8', text: '#422006', border: '#92400e' },
    borderStyle: 'classic',
    sealStyle: 'laurel',
    titleLine1: 'VOLUNTEER',
    titleLine2: 'CERTIFICATE',
    defaultDescription: 'is gratefully recognized for their volunteer service to',
  },
  {
    id: 'workshop',
    name: 'Workshop Certificate',
    category: 'Events',
    description: 'Creative certificate for workshop attendees',
    colors: { primary: '#3730a3', secondary: '#06b6d4', background: '#eef2ff', text: '#1e1b4b', border: '#3730a3' },
    borderStyle: 'elegant',
    sealStyle: 'ribbon-badge',
    titleLine1: 'WORKSHOP',
    titleLine2: 'CERTIFICATE',
    defaultDescription: 'has successfully completed the workshop on',
  },
  {
    id: 'webinar',
    name: 'Webinar Certificate',
    category: 'Events',
    description: 'Clean certificate for webinar and online event participants',
    colors: { primary: '#0369a1', secondary: '#bae6fd', background: '#f0f9ff', text: '#0c4a6e', border: '#0369a1' },
    borderStyle: 'minimal',
    sealStyle: 'none',
    titleLine1: 'WEBINAR',
    titleLine2: 'CERTIFICATE',
    defaultDescription: 'has attended the webinar on',
  },
  {
    id: 'custom',
    name: 'Custom Certificate',
    category: 'Custom',
    description: 'Fully customizable blank certificate template',
    colors: { primary: '#1f2937', secondary: '#F0B429', background: '#ffffff', text: '#1f2937', border: '#d1d5db' },
    borderStyle: 'minimal',
    sealStyle: 'none',
    titleLine1: 'CERTIFICATE',
    titleLine2: '',
    defaultDescription: 'is hereby certified for',
  },
];

export const getTemplate = (id) => templates.find((t) => t.id === id) || templates[templates.length - 1];
export const getTemplatesByCategory = (category) =>
  category === 'All' ? templates : templates.filter((t) => t.category === category);
